on: push

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Install checking tools
        run: |
          sudo apt update && sudo apt install clang clang-tidy python3 python3-pip && sudo pip install cpplint
      - name: Run checkers
        run: |
          cpplint --extensions=c,h *.c num_lib/shared/* num_lib/static/* num_lib/common/inc/* > cpplint_result.txt 2>&1
          clang-tidy num_lib/static/* numbers.c -extra-arg=-std=gnu11 -- -I num_lib/common/inc > clang_result.txt 2>&1 || exit 0
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            cpplint_result.txt
            clang_result.txt
  Build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - name: Install GTest
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest && mkdir build && cd build && cmake .. && cmake --build . && sudo cmake --install . && cd ../..
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. && cmake --build .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            build/numbers_shared
            build/numbers_static
      - name: Install valgrind and report software
        run: |
          sudo apt update && sudo apt install valgrind lcov
      - name: Run tests
        run: |
          cd build
          valgrind --leak-check=full -s --log-file=valgrind_tests_shared_report.txt ./tests/num_test_shared
          valgrind --leak-check=full -s --log-file=valgrind_tests_static_report.txt ./tests/num_test_static
          lcov -o coverage.info -c -d num_lib/ && genhtml -o coverage_report coverage.info
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/coverage_report/
            build/valgrind_tests_shared_report.txt
            build/valgrind_tests_static_report.txt
